name: Push to Replicate

on:
  push:
    branches: [ main ]  # Or your default branch name
  workflow_dispatch:    # Allows manual triggering

jobs:
  push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Install Cog
      run: |
        curl -o cog -L https://github.com/replicate/cog/releases/latest/download/cog_Linux_x86_64
        chmod +x cog
        sudo mv cog /usr/local/bin/
        cog --version
    
    - name: Login to Replicate
      run: cog login --token ${{ secrets.REPLICATE_API_TOKEN }}
    
    - name: Push to Replicate
      run: cog push r8.im/${{ secrets.REPLICATE_USERNAME }}/${{ secrets.REPLICATE_MODEL_NAME }}
